import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { isLocale } from "@/lib/i18n";

export const metadata: Metadata = {
  title: "About KoreaTravel",
  description:
    "Learn what KoreaTravel does, how recommendations are generated, and which public data sources are used."
};

export default async function AboutPage({
  params
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();

  return (
    <section className="space-y-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm">
      <h1 className="text-3xl font-bold text-slate-900">About KoreaTravel</h1>
      <p className="text-slate-700">
        KoreaTravel is an English-first planning guide for international visitors to South Korea.
        We publish original destination summaries, itinerary suggestions, and map-based exploration
        tools to help travelers compare regions before booking.
      </p>
      <p className="text-slate-700">
        Recommendation results are generated by our internal scoring engine using user quiz answers,
        trip style, duration, transport preferences, and language needs. We do not copy social reviews.
      </p>
      <div className="rounded-2xl bg-slate-50 p-4">
        <h2 className="text-lg font-semibold text-slate-900">Data Sources</h2>
        <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-700">
          <li>Korea Tourism Organization TourAPI (official public tourism data)</li>
          <li>KTO tourism photo APIs where available</li>
          <li>Official map/search links such as Google Maps search URLs</li>
        </ul>
      </div>
      <p className="text-xs text-slate-500">Last updated: 2026-02-26</p>
    </section>
  );
}
